### PR TITLE
Little bit of refactoring and a PublishedModelDetailView

### PR DESCRIPTION
**Pull request by tswicegood**

### CODE REVIEW

**Comment by niran** [comment]
What about `PublishedModelListView`? The logic you've added could be broken out into a mixin and mixed in to both `DetailView` and `ListView`.

**Comment by tswicegood** [comment]
That could work.  As I was writing this code, I'd actually considered extracting the `PublishedManager` code so it doesn't rely on `Model.published` and can filter anything so long as they have the correct fields.

**Comment by niran** [comment]
This looks ready to go once the `ListView` is in.

**Comment by tswicegood** [comment]
This is ready now.  I've reorganized all of the publication code to live under the `arm_content.publication` module.  For convenience (and backwards compatibility in some cases), I've imported all of the relevant module variables into their top-level `arm_content` counterparts.

**Pull request closed without merging**
