### PR TITLE
Update publication.py

### PR DESCRIPTION
**Pull request by ScottBarkman**
Need to pass in the datetime.now function reference so that date is captured at run time. Was causing date to be static on server start.

### CODE REVIEW

**Comment by Jbonnett** [comment]
This is a problem, however this solution wont work. The problem you are seeing is in the manager, not that function.  What I did was replace the provided published manager, with one that uses the db(!) to get the current time at query execution time. Provided code is for mysql only. I feel this should be handled in ORM level as many class based views are going to get caught with this problem. 

``` python
class PublishedManager(InheritanceManager):
    """ Returns published objects where the pub_date has already passed """
    def get_query_set(self):
        return super(PublishedManager, self).get_query_set()\
                .filter(pub_status="P")\
                .extra(where=["pub_date <= now()"])
```

**Comment by Jbonnett** [comment]
P.S. Thanks for the contribution! Any help fixing this upstream would be awesome. For instance, if you have a version of the above for for postgres, that would be excellent.

**Comment by Jbonnett** [comment]
I am going to close this, because the code change is in the manager, not that function. This doesnt mean we dont need to fix the bug you speak of, it just means THIS patch isn't quite going to do it.

**Comment by ScottBarkman** [comment]
Sorry - didn't see these over the weekend. Yea - I realized this after the quick (premature) pull request. Baring work loads, I'll try and get you a proper pull request.

**Comment by joncotton** [comment]
Imma chime in on this too but I'm going to do the bulk of reasoning over here #31 (haha yeah...that's been sitting there a while). @Jbonnett what you have works, but it's complicated, database specific and might interfere with other QuerySet `pub_date` filtering/excluding. Thankfully it isn't necessary.

Also, sorry for slow response, was on vacation.

**Pull request closed without merging**
